# Generated by Django 3.1.7 on 2021-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
